### ISSUE TITLE
bench: standalone fuzzy finder for benchmarking against other implementations

### ISSUE THREAD

**Issue by matu3ba** [helix-editor/nucleo#22]
See https://github.com/jake-stewart/jfind/issues/19 for context.

At least in the linked asciinema it is significantly slower, but I'm not sure for the exact reasons.
Startup time should be negligible for non-tiny datasets, so a fuzzer cli frontend would be easiest to use for fair comparison.

**Comment by pascalkuthe** [comment]
I find that comparison very odd. You are benchmarking how long it takes to stream in a file. That is limited by the file transversal which is not part of the matcher. In thus case helix is ofcourse slower because it runs the file transversal on a single thread and sorts all files.

I made that design choice deliberately since I find sorted files more important than how fast files stream in. Nucleo has fully lock and wait free input so it's as fast as your input stream is.

When I compared nucleo to fzf I was comparison matching speed *after the stream had complemented* since that is what fuzzy matchers actually do (and the stream in nucleo can never backlog).


Either way while a CLI would be nice I just don't have the time for that right now.

**Comment by egrieco** [comment]
> Either way while a CLI would be nice I just don't have the time for that right now.

Well, I needed a CLI fuzzy finder for a project so I built one: [picleo](https://crates.io/crates/picleo)

It's still **very alpha stage** software, but I've been cleaning it up and adding the functionality I need.

## Background

I need a fuzzy finder that:

1. Can handle selection of multiple items
2. Allows for the creation of items not originally in the matching set
3. Has filtering options for fields besides those shown and fuzzy matched against
4. Is fast for large numbers of items
5. Allows the core functionality to be embedded in other software as a library
6. Can wrap arbitrary object types and return the whole objects after matches

I tried using [skim](https://crates.io/crates/skim). While I got it integrated, it was a bit awkward and I couldn't customize it's behavior to meet all of my needs.

[nucleo-picker](https://crates.io/crates/nucleo-picker) looked promising, but ultimately did not have all of the features I needed.
